name: Update Vosker Image

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install selenium requests

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run script
        run: python garbage.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
